# Generated by Django 5.0.1 on 2024-02-09 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("inventory", "0001_initial"),
        ("product_inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.inventory"
            ),
        ),
        migrations.AddField(
            model_name="analytics",
            name="product_inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="product_inventory.productinventory",
            ),
        ),
        migrations.AddField(
            model_name="analytics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
