# Generated by Django 5.0.1 on 2024-02-09 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("raw_material", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterialOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0)),
                ("raw_materials_order", models.JSONField(blank=True, null=True)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ordered"), (2, "In Transit"), (3, "Delivered")],
                        default=1,
                    ),
                ),
                (
                    "analytics",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_material_orders",
                        to="analytics.analytics",
                    ),
                ),
                (
                    "raw_materials",
                    models.ManyToManyField(blank=True, to="raw_material.rawmaterial"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
