# Generated by Django 5.0.1 on 2024-02-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product_inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity_available", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "production_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=250, null=True)),
                ("raw_material_requirements", models.JSONField(blank=True, null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="product_inventory.productinventory",
                    ),
                ),
            ],
        ),
    ]
