# Generated by Django 5.0.1 on 2024-02-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "production_status",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "In Progress"),
                            (3, "Quality Control"),
                            (4, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ClientOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_note", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("delivery_time", models.DurationField(blank=True, null=True)),
                ("processing_time", models.DurationField(blank=True, null=True)),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "In Progress"),
                            (3, "Quality Control"),
                            (4, "Ready for Shipping"),
                            (5, "In Transit"),
                            (6, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                ("nr_products", models.IntegerField(default=0)),
                ("nr_products_completed", models.IntegerField(default=0)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "analytics",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_orders",
                        to="analytics.analytics",
                    ),
                ),
            ],
        ),
    ]
