# Generated by Django 5.0.1 on 2024-02-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("quantity_available", models.IntegerField(default=0)),
                ("restock_required", models.BooleanField(default=False)),
                ("max_quantity", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.inventory",
                    ),
                ),
            ],
        ),
    ]
