name: factoryforge
dependencies:
  - python=3.12.1
  - pip:
      - django==5.0.1
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.3.1
      - drf-yasg==1.21.7
      - Pillow==10.2.0
      - Markdown==3.5.2
      - django-dotenv==1.4.2
      - whitenoise==6.6.0
      - django-storages==1.14.2
      - boto3==1.34.28
      - psycopg2-binary==2.9.9
      - gunicorn==21.2.0
      - dj-database-url==2.1.0
      - django-cors-headers==4.3.1